# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JDGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QWidget, QCheckBox, QApplication, QPushButton, QMessageBox,QMainWindow,QInputDialog,QTextEdit
from PyQt5.QtCore import Qt
import re
from eachTable import eachTable_MainWindow
from NoteBook import NoteBook
import openpyxl as ol
import os

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, MainWindow):
        print('ok')
        self.paths = '文件管理.xlsx'
        self.wb = ol.load_workbook(self.paths)
        self.allSheets = self.wb.sheetnames
        self.itemNo = 0
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        MainWindow.setMinimumSize(QtCore.QSize(800, 650))
        MainWindow.setMaximumSize(QtCore.QSize(800, 650))
        MainWindow.move(250,10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Pic/Metal1.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(210, 30, 350, 44))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.TITLE.setFont(font)
        self.TITLE.setObjectName("TITLE")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(50, 80, 701, 20))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 115, 135, 32))
        font = QtGui.QFont()
        font.setFamily("叶根友毛笔行书修正版")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.chooseSheets = QtWidgets.QComboBox(self.centralwidget)
        self.chooseSheets.setGeometry(QtCore.QRect(200, 110, 361, 41))
        self.chooseSheets.addItems(self.allSheets)
        self.chooseSheets.setCurrentIndex(7)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.chooseSheets.setFont(font)
        self.chooseSheets.setWhatsThis("")
        self.chooseSheets.setAccessibleDescription("")
        self.chooseSheets.setObjectName("chooseSheets")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(50, 160, 701, 20))
        self.line_2.setLineWidth(2)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 193, 100, 24))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 193, 101, 24))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.label_Amount = QtWidgets.QLabel(self.centralwidget)
        self.label_Amount.setGeometry(QtCore.QRect(560, 193, 100, 24))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setBold(False)
        font.setWeight(50)
        self.label_Amount.setFont(font)
        self.label_Amount.setObjectName("label_Amount")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(680, 193, 50, 24))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(50, 220, 701, 20))
        self.line_3.setLineWidth(1)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(50, 230, 721, 321))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.VLine)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 700, 10))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 193, 46, 24))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ShougongButton = QtWidgets.QPushButton(self.centralwidget)
        self.ShougongButton.setGeometry(QtCore.QRect(250, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("文鼎妞妞体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ShougongButton.setFont(font)
        self.ShougongButton.setObjectName("ShougongButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 110, 150, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 570, 251, 21))
        self.label_7.setObjectName("label_7")
        self.label_pageno = QtWidgets.QLabel(self.centralwidget)
        self.label_pageno.setGeometry(QtCore.QRect(570, 570, 61, 20))
        self.label_pageno.setObjectName("label_pageno")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(690, 570, 42, 22))
        self.spinBox.setWrapping(True)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(200)
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setValue(1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(640, 565, 41, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(740, 570, 21, 20))
        self.label_9.setObjectName("label_9")
        self.label_pageno_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_pageno_2.setGeometry(QtCore.QRect(450, 570, 111, 20))
        self.label_pageno_2.setObjectName("label_pageno_2")

        MainWindow.setCentralWidget(self.centralwidget)

        self.Old = 0
        self.h=2

        #设好位置，录入结果
        filesNames=[]
        self.dicts = []
        allFiles = os.walk('./文件')
        for root, dirs, files in allFiles:
            self.dicts.append(root)
            filesNames.append(files)  # 当前路径下所有非目录子文件
        self.filesNames = str(filesNames)
        print(self.filesNames)

        self.ShougongButton.clicked.connect(self.showEach)
        self.pushButton_3.clicked.connect(self.reload)
        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def reload(self):
        self.sheetnames = self.chooseSheets.currentText()
        self.note = NoteBook(self.paths, self.sheetnames)
        self.label_2.setText("<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">买方</span></p></body></html>")
        self.label_3.setText("<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">合同号码</span></p></body></html>")
        self.label_Amount.setText("<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">合同金额</span></p></body></html>")
        self.itemNo = self.note.ZhuanZu['序号']
        self.Buyer = self.note.ZhuanZu['买方']
        self.ContractNo = self.note.ZhuanZu['合同号']
        self.Amount = self.note.ZhuanZu['金额']

        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 700, 10+30*len(self.itemNo)))
        self.commoditieslist ={}
        for j,Buyer,Amount,ContractNo in zip(range(1,len(self.itemNo)+1),self.Buyer,self.Amount,self.ContractNo):
            exec('''
try:self.subline{i}.deleteLater()
except:pass
self.subline{i} = QtWidgets.QFrame(self.scrollAreaWidgetContents)
self.subline{i}.setGeometry(QtCore.QRect(-10, {x}, 701, 20))
self.subline{i}.setLineWidth(1)
self.subline{i}.setMidLineWidth(0)
self.subline{i}.setFrameShape(QtWidgets.QFrame.HLine)
self.subline{i}.setFrameShadow(QtWidgets.QFrame.Sunken)
self.subline{i}.setObjectName("subline{i}")
self.subline{i}.show()

try:self.label_no{i}.deleteLater()
except:pass
self.label_no{i} = QtWidgets.QLabel(self.scrollAreaWidgetContents)
self.label_no{i}.setGeometry(QtCore.QRect(0, {y}, 40, 18))
font = QtGui.QFont()
font.setFamily("楷体")
font.setBold(False)
font.setWeight(50)
self.label_no{i}.setFont(font)
self.label_no{i}.setObjectName("label_no{i}")
self.label_no{i}.setText("<html><head/><body><p><span style=' font-size:12pt;'>{i}.</span></p></body></html>")
self.label_no{i}.show()

try:self.Buyer{i}.deleteLater()
except:pass
self.Buyer{i} = QtWidgets.QLabel(self.scrollAreaWidgetContents)
self.Buyer{i}.setGeometry(QtCore.QRect(50, {y}, 180, 18))
font = QtGui.QFont()
font.setFamily("楷体")
font.setBold(False)
font.setWeight(50)
self.Buyer{i}.setFont(font)
self.Buyer{i}.setObjectName("Buyer{i}")
self.Buyer{i}.setText("<html><head/><body><p><span style=' font-size:12pt;'>{Buyer}</span></p></body></html>")
self.Buyer{i}.setToolTip("{Buyer}")
self.Buyer{i}.show()

try:self.ContractNo{i}.deleteLater()
except:pass
self.ContractNo{i} = QtWidgets.QLabel(self.scrollAreaWidgetContents)
self.ContractNo{i}.setGeometry(QtCore.QRect(250, {y}, 240, 18))
font = QtGui.QFont()
font.setFamily("楷体")
font.setBold(False)
font.setWeight(50)
self.ContractNo{i}.setFont(font)
self.ContractNo{i}.setObjectName("ContractNo{i}")
self.ContractNo{i}.setText("<html><head/><body><span style=' font-size:12pt;'>{ContractNo}</span></p></body></html>")
self.ContractNo{i}.setOpenExternalLinks(True)
self.ContractNo{i}.setToolTip("{ContractNo}")
self.ContractNo{i}.show()

try:self.Amount{i}.deleteLater()
except:pass
self.Amount{i} = QtWidgets.QLabel(self.scrollAreaWidgetContents)
self.Amount{i}.setGeometry(QtCore.QRect(500, {y}, 100, 18))
font = QtGui.QFont()
font.setFamily("楷体")
font.setBold(False)
font.setWeight(50)
self.Amount{i}.setFont(font)
self.Amount{i}.setObjectName("ContractNo{i}")
self.Amount{i}.setText("<html><head/><body><p align='right'><span align='right' style=' font-size:12pt;text-align: right '>{Amount}</span></p></body></html>")
self.Amount{i}.setToolTip("{Amount}")
self.Amount{i}.show()

try:self.DownloadButton_v{i}.deleteLater()
except:pass
self.DownloadButton_v{i} = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
self.DownloadButton_v{i}.setGeometry(QtCore.QRect(615, {y}, 61, 20))
self.DownloadButton_v{i}.setObjectName("DownloadButton_v{i}")
self.DownloadButton_v{i}.setText("合同详情")
self.DownloadButton_v{i}.show()
self.DownloadButton_v{i}.clicked.connect(self.showEach)

self.commoditieslist['DownloadButton_v{i}']={i}-1
'''.format(i=int(j),x=j * 30,y = 15+(j-1)*30,Buyer = Buyer,ContractNo = ContractNo,Amount = Amount))

    def showEach(self):
        senderno = self.sender().objectName()
        print(senderno)
        print(self.sender())
        if self.sender() ==self.ShougongButton:
            contractWindow.Old = 1
            contractWindow.sheetname=self.sheetnames
            contractWindow.showDetails(self.paths, self.sheetnames, 0)
            contractWindow.chongzhi.click()
            contractWindow.show()
        else:
            contractWindow.Old = 0
            contractWindow.sheetname=self.sheetnames
            contractWindow.h = int(self.commoditieslist[senderno])
            contractWindow.showDetails(self.paths,self.sheetnames,self.commoditieslist[senderno])
            contractNoofFile = self.ContractNo.iloc[self.commoditieslist[senderno]]

            try:
                oneFIle = re.findall("'{}.*?\.docx'".format(contractNoofFile), self.filesNames)[0]
            except:
                quest = QMessageBox.information(self,'找不到文件','找不到文件',QMessageBox.Ok)
                oneFIle='WHAT EVER'

            for d in self.dicts:
                print(d)
                if oneFIle== 'WHAT EVER':
                    contractWindow.FilePath = ''
                    break
                if os.path.exists(d + '\\' + oneFIle.strip("'")):
                    contractWindow.FilePath = d+'\\'+oneFIle.strip("'")
                    print(contractWindow.FilePath)
                    break
                else:
                    continue
            contractWindow.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文件管理器"))
        self.TITLE.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">文件管理器</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffaa00;\">表格列表</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">买方</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">合同编号</span></p></body></html>"))
        self.label_Amount.setText(_translate("MainWindow","<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">合同金额</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">打开</span></p></body></html>"))
        self.scrollArea.setStatusTip(_translate("MainWindow", "合同列表"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">序号</span></p></body></html>"))
        self.ShougongButton.setStatusTip(_translate("MainWindow", "新建合同"))
        self.ShougongButton.setText(_translate("MainWindow", "新建合同"))
        self.ShougongButton.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.pushButton_3.setStatusTip(_translate("MainWindow", "打开工作簿"))
        self.pushButton_3.setText(_translate("MainWindow", "打开工作簿"))
        self.label_7.setStatusTip(_translate("MainWindow", "下载进度"))
        self.label_7.setText(_translate("MainWindow", " "))
        self.label_pageno.setStatusTip(_translate("MainWindow", "当前页码"))
        self.label_pageno.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">第 页</span></p></body></html>"))
        self.spinBox.setStatusTip(_translate("MainWindow", "页数"))
        self.pushButton_4.setStatusTip(_translate("MainWindow", "按一次跳转页数会自动递增"))
        self.pushButton_4.setText(_translate("MainWindow", "跳转"))
        self.label_9.setText(_translate("MainWindow", "页"))
        self.label_pageno_2.setStatusTip(_translate("MainWindow", "所搜索的关键字"))
        self.label_pageno_2.setText(_translate("MainWindow", "<html><head/><body><p>结果</p></body></html>"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow1 = QMainWindow()
    ui = Ui_MainWindow()
    contractWindow = eachTable_MainWindow()
    ui.setupUi(MainWindow1)
    MainWindow1.show()
    sys.exit(app.exec_())